spring:
  application:
    name: lab-3-spring-data
  datasource:
    password: apple
    url: jdbc:postgresql://localhost:5432/spring-aop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
